version: 0.2

env:
  parameter-store:
    VITE_CHATTEX_API_URL: "VITE_CHATTEX_API_URL_DEV"
    VITE_CHATTEX_WEBSOCKET_API_URL: "VITE_CHATTEX_WEBSOCKET_API_URL_DEV"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 22
  pre_build:
    on-failure: ABORT
    commands:
      - npm ci
  build:
    on-failure: ABORT
    commands:
      - npm run build
  # post_build:
  #   on-failure: ABORT
  #   commands:
  #     - aws s3 sync dist/ s3://chattex-frontend-dev --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
