version: 0.2

env:
  variables:
    VITE_CHATTEX_DEV: "true"
  parameter-store:
    VITE_CHATTEX_API_URL: "/CHATTEX_DEV/API_URL"
    VITE_CHATTEX_WEBSOCKET_API_URL: "/CHATTEX_DEV/WEBSOCKET_API_URL"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 22
  pre_build:
    on-failure: ABORT
    commands:
      - cd frontend
      - npm ci
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    on-failure: ABORT
    commands:
      - aws s3 sync dist/ s3://chattex-frontend-dev/ --cache-control "public, max-age=86400, immutable" --exclude "index.html"
      - aws s3 cp dist/index.html s3://chattex-frontend-dev/index.html --cache-control "public, max-age=300"

# artifacts:
#   files:
#     - '**/*'
#   base-directory: frontend/dist
